# Site settings

title: afdal # Title of your site
email: afdalp@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     https://twitter.com/amandaputra
github_username:      https://github.com/afdalarif  
linkedin_username:    # Replace this with your LinkedIn username
google_plus_username: https://plus.google.com/u/0/106479458672671828716/about
facebook_username:    https://www.facebook.com/profile.php?id=100000662149017
dribbble_username:      # Replace this with your Dribbble username

# Build settings
markdown: kramdown
